services:
  - type: web
    name: os-gestao
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn visual:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4 