services:
  - type: web
    name: ordens-servico-compuword
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python visual.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16 